const timelineData = [
  { year: 2025, title: "Communications and Social Media Officer", subtitle: "Tata Institute of Social Sciences (TISS)", description: "Promoted to Communications and Social Media Officer, focusing on strategic communication, social media management, public relations, and brand management.", category: "Work Experience", icon: "briefcase" },
  { year: 2024, title: "M.A. in Education and Technology", subtitle: "Tata Institute of Social Sciences, Mumbai", description: "Completed M.A. in Education and Technology (A- grade). Capstone: “Using AI to Design and Develop Multimedia Artefacts for an Online (MOOC) Course”.", category: "Education", icon: "book-open" },
  { year: 2023, title: "Start of Project Ankur (MP)", subtitle: "Govt of Madhya Pradesh Rajya Shiksha Kendra", description: "Began supporting communications and training resource materials for Project Ankur (May 2023 - April 2025).", category: "Project", icon: "zap" },
  { year: 2022, title: "Start of STARS Project", subtitle: "KPMG", description: "Began providing ongoing communications and support for the STARS project (Dec 2022 - Dec 2025).", category: "Project", icon: "star" },
  { year: 2021, title: "Start of CLIx Phase II", subtitle: "Connected Learning Initiative", description: "Continued communications and content development for CLIx phase II, including online resources (Apr 2020 - Mar 2023).", category: "Project", icon: "code" },
  { year: 2020, title: "Operationalizing CETE as National Nodal Centre", subtitle: "Centre of Excellence in Teacher Education (CETE), TISS", description: "Began key communications and operational support for establishing CETE as the national nodal centre (June 2020 - May 2028).", category: "Work Experience", icon: "award" },
  { year: 2019, title: "NHRC Research on Child Labourers", subtitle: "National Human Rights Commission", description: "Provided research communications and report design for NHRC study on mainstreaming child labourers in schools (Nov 2019 - Jan 2021).", category: "Project", icon: "users" },
  { year: 2018, title: "Establishing CETE", subtitle: "Centre of Excellence in Teacher Education (CETE), TISS", description: "Supported the initial set up and communications for CETE at TISS including branding and content curation (June 2018 - May 2020).", category: "Work Experience", icon: "settings" },
  { year: 2017, title: "Experienced PR Professional Role", subtitle: "Centre of Excellence in Teacher Education (CETE), TISS", description: "Began role as an experienced PR professional, developing strategic communication plans and designing various communication materials (Sept 2017 - April 2025).", category: "Work Experience", icon: "message-square" },
  { year: 2017, title: "Resource Assistant", subtitle: "Dr. Naina Athale (Development Management Institute)", description: "Provided E-resources from the Internet (Feb 2017 - Aug 2017).", category: "Work Experience", icon: "search" },
  { year: 2016, title: "Field Work: Special Cell for Women and Children", subtitle: "Belapur, Navi Mumbai", description: "Worked for women who are the survivals of Domestic Violence, providing counselling and coordinating with police/hospitals (June 2016 - Dec 2016).", category: "Field Work", icon: "heart" },
  { year: 2015, title: "M.A. in Social Work in Children and Families", subtitle: "Tata Institute of Social Sciences, Mumbai", description: "Completed M.A. in Social Work in Children and Families (B+ grade).", category: "Education", icon: "book" },
  { year: 2015, title: "Field Work: YUVA", subtitle: "Youth for Unity and Voluntary Action", description: "Accomplished Registering 150 Labour Cards, Community Profiling, and established an Anganwadi (July 2015 - March 2016).", category: "Field Work", icon: "home" },
  { year: 2015, title: "Bachelors in Commerce", subtitle: "N.G. Acharya & D.K. Marathe College, Mumbai", description: "Completed Bachelors in Commerce (B grade).", category: "Education", icon: "dollar-sign" },
  { year: 2014, title: "Business Facilitator/Correspondent", subtitle: "NSDC", description: "Worked as a Business Facilitator and/or Business Correspondent (2014-15).", category: "Work Experience", icon: "trending-up" },
];

if (typeof window !== 'undefined') window.timelineData = timelineData;
if (typeof module !== 'undefined' && module.exports) module.exports = timelineData;
